# Generated by Django 5.2.7 on 2025-10-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='message_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='wa_sender_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'PendPendienteing'), ('completed', 'Completada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='worksite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
