# Generated by Django 5.2.7 on 2025-10-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_message_sent_at_expense_wa_sender_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Sin Categoria', max_length=128),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Parametrizado'), ('approved', 'Aprobado'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
    ]
