# Generated by Django 5.2.7 on 2025-12-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_category_alter_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='document_type',
            field=models.CharField(blank=True, choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('vale', 'Vale')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('alojamiento', 'Alojamiento'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='vehicle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='wa_media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='worksite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
