# Generated by Django 5.2.7 on 2026-01-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_document_type_expense_expense_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('manual', 'Manual'), ('synced', 'Sincronizado'), ('failed', 'Error')], default='manual', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo/Maquinaria',
                'verbose_name_plural': 'Vehículos/Maquinarias',
            },
        ),
        migrations.CreateModel(
            name='WorksiteCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('manual', 'Manual'), ('synced', 'Sincronizado'), ('failed', 'Error')], default='manual', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Obra/Proyecto',
                'verbose_name_plural': 'Obras/Proyectos',
            },
        ),
    ]
