# Generated by Django 5.2.7 on 2026-01-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_allowedsender_vehiclecatalog_worksitecatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedsender',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
