# Generated by Django 5.2.7 on 2026-01-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_allowedsender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedsender',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
