# Generated by Django 5.2.7 on 2026-01-14 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_allowedsender_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='wa_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.allowedsender'),
        ),
    ]
