# Generated by Django 5.2.7 on 2026-06-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_rindegastos_catalog_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='rindegastos_cost_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='rindegastos_document_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
