# Generated by Django 5.2.7 on 2026-08-06 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0035_rindegastos_reconcile_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RindegastosExpenseDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=128)),
                ('local_value', models.JSONField(blank=True, null=True)),
                ('remote_value', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('conflict', 'Conflicto')], default='info', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('applied', 'Aplicada'), ('ignored', 'Ignorada'), ('resolved', 'Resuelta')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rindegastos_diffs', to='expenses.expense')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='expenses.rindegastosexpensesnapshot')),
            ],
            options={
                'verbose_name': 'Diferencia gasto Rindegastos',
                'verbose_name_plural': 'Diferencias gastos Rindegastos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['expense', 'status'], name='expenses_ri_expense_f3a2f6_idx'), models.Index(fields=['snapshot', 'field_name'], name='expenses_ri_snapsho_85d3b0_idx')],
            },
        ),
    ]
