# Generated by Django 5.2.7 on 2026-08-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0036_rindegastos_expense_diff'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFundMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_beneficiary_name', models.CharField(max_length=255)),
                ('rut', models.CharField(blank=True, max_length=32)),
                ('rindegastos_fund_id', models.CharField(blank=True, max_length=255)),
                ('rindegastos_admin_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rindegastos_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_mappings', to='expenses.rindegastosusercatalog')),
            ],
            options={
                'verbose_name': 'Mapeo fondo trabajador',
                'verbose_name_plural': 'Mapeos fondos trabajadores',
            },
        ),
        migrations.CreateModel(
            name='NotionFundSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_page_id', models.CharField(max_length=255, unique=True)),
                ('notion_url', models.URLField(blank=True, max_length=1000)),
                ('notion_status', models.CharField(blank=True, max_length=255)),
                ('notion_work_key', models.CharField(blank=True, max_length=255)),
                ('notion_record_id', models.CharField(blank=True, max_length=255)),
                ('beneficiary_name', models.CharField(blank=True, max_length=255)),
                ('beneficiary_rut', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='CLP', max_length=8)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=255)),
                ('local_status', models.CharField(choices=[('pending', 'Pendiente'), ('validated', 'Validado'), ('ready', 'Listo para abono'), ('error', 'Error'), ('ignored', 'Ignorado'), ('rindegastos_ok', 'Rindegastos OK'), ('notion_ok', 'Notion actualizado'), ('rindegastos_ok_notion_error', 'Rindegastos OK / Notion error')], db_index=True, default='pending', max_length=40)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64)),
                ('rindegastos_fund_id', models.CharField(blank=True, max_length=255)),
                ('rindegastos_deposit_id', models.CharField(blank=True, max_length=255)),
                ('notion_raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('rindegastos_request_payload', models.JSONField(blank=True, default=dict)),
                ('rindegastos_response_payload', models.JSONField(blank=True, default=dict)),
                ('notion_update_payload', models.JSONField(blank=True, default=dict)),
                ('notion_update_response', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notion_sync_logs', to='expenses.employeefundmapping')),
                ('rindegastos_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notion_fund_sync_logs', to='expenses.rindegastosusercatalog')),
            ],
            options={
                'verbose_name': 'Log sync fondo Notion',
                'verbose_name_plural': 'Logs sync fondos Notion',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddIndex(
            model_name='employeefundmapping',
            index=models.Index(fields=['rut', 'is_active'], name='expenses_em_rut_6a7efc_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefundmapping',
            index=models.Index(fields=['notion_beneficiary_name', 'is_active'], name='expenses_em_notion__ef9bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='notionfundsynclog',
            index=models.Index(fields=['local_status', 'updated_at'], name='expenses_no_local_s_a6e741_idx'),
        ),
        migrations.AddIndex(
            model_name='notionfundsynclog',
            index=models.Index(fields=['beneficiary_rut', 'local_status'], name='expenses_no_benefic_86a088_idx'),
        ),
        migrations.AddIndex(
            model_name='notionfundsynclog',
            index=models.Index(fields=['idempotency_key', 'local_status'], name='expenses_no_idempot_f54a11_idx'),
        ),
    ]
