# Generated by Django 5.2.7 on 2026-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0037_employeefundmapping_notionfundsynclog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notionfundsynclog',
            name='local_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('pending_mapping', 'Pendiente mapeo'), ('validated', 'Validado'), ('ready', 'Listo para abono'), ('error', 'Error'), ('ignored', 'Ignorado'), ('rindegastos_ok', 'Rindegastos OK'), ('notion_ok', 'Notion actualizado'), ('rindegastos_ok_notion_error', 'Rindegastos OK / Notion error')], db_index=True, default='pending', max_length=40),
        ),
    ]
