# Generated by Django 5.2.7 on 2026-08-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0038_alter_notionfundsynclog_local_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionfundsynclog',
            name='notion_rindegastos_fund',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
