from django.urls import path
from .views import (
    dashboard,
    expense_action,
    expense_create,
    expense_detail,
    expense_list,
    expense_rindegastos_export,
    rindegastos_policy_options,
    attachment_serve,
    settings_view,
    settings_categories,
    settings_expense_types,
    settings_rindegastos_fields,
    settings_system_users,
    settings_suppliers,
    settings_users,
    settings_worksites,
)
urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("gastos/", expense_list, name="expense_list"),
    path("expenses/create/", expense_create, name="expense_create"),
    path("expenses/export/rindegastos/", expense_rindegastos_export, name="expense_rindegastos_export"),
    path(
        "expenses/rindegastos/policies/<str:external_id>/options/",
        rindegastos_policy_options,
        name="rindegastos_policy_options",
    ),
    path("expenses/<int:pk>/", expense_detail, name="expense_detail"),
    path("expenses/<int:pk>/action/<str:action>/", expense_action, name="expense_action"),
    path("attachments/<int:pk>/", attachment_serve, name="attachment_serve"),
    path("configuracion/", settings_view, name="settings"),
    path("configuracion/usuarios-sistema/", settings_system_users, name="settings_system_users"),
    path("configuracion/usuarios/", settings_users, name="settings_users"),
    path("configuracion/obras/", settings_worksites, name="settings_worksites"),
    path("configuracion/proveedores/", settings_suppliers, name="settings_suppliers"),
    path("configuracion/categorias/", settings_categories, name="settings_categories"),
    path("configuracion/tipos-gasto/", settings_expense_types, name="settings_expense_types"),
    path(
        "configuracion/campos-rindegastos/",
        settings_rindegastos_fields,
        name="settings_rindegastos_fields",
    ),
]
